### ISSUE TITLE
Error entering to mezeporta

### ISSUE THREAD

**Issue by halexys** [ZeruLight/Erupe#37]
i got this error when entering to mezeporta 
Recovered from panic runtime error: invalid memory address or nil pointer dereference.
its happen with old characters, if a create a new one the error doesn't happens

**Comment by sekaiwish** [comment]
This is not enough information to be able to diagnose any sort of server-side issue.
Please enable LogInboundMessages and LogOutboundMessages in the config and post relevant server output alongside your issue.

**Comment by Tsugami** [comment]
"BigBosSs" is your nick?

your message doesn't have enough content to find the problem

https://github.com/ZeruLight/Erupe/blob/ba927f877d4611df0a6bee81e2cc2a627e3d5ecb/server/channelserver/sys_session.go#L185-L191

comment on the `recover` and send the logs here again. Whenever I need to debug in my server, I remove recover. otherwise it will always return  `invalid memory address or nil pointer dereference`

**Comment by halexys** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x85d21e]

goroutine 51 [running]:
erupe-ce/server/channelserver.handleMsgMhfInfoFesta(0xc0002841a0, {0xa9cea0, 0xc000296170})
        D:/Games/MHFZ_Test/Launcher/Erupe-main/server/channelserver/handlers_festa.go:154 +0x1be
erupe-ce/server/channelserver.(*Session).handlePacketGroup(0xc0002841a0, {0xc000296150, 0xc, 0x10})
        D:/Games/MHFZ_Test/Launcher/Erupe-main/server/channelserver/sys_session.go:211 +0x1d2
erupe-ce/server/channelserver.(*Session).recvLoop(0xc0002841a0)
        D:/Games/MHFZ_Test/Launcher/Erupe-main/server/channelserver/sys_session.go:176 +0x46
erupe-ce/server/channelserver.(*Session).Start.func1()
        D:/Games/MHFZ_Test/Launcher/Erupe-main/server/channelserver/sys_session.go:97 +0x15e
created by erupe-ce/server/channelserver.(*Session).Start
        D:/Games/MHFZ_Test/Launcher/Erupe-main/server/channelserver/sys_session.go:92 +0x5b


This is the log without the recover function.

**Comment by sekaiwish** [comment]
This error culminates from line 154 of handlers_festa.

https://github.com/ZeruLight/Erupe/blob/df1a4834ba95f06bd9e193481af1722988bc58aa/server/channelserver/handlers_festa.go#L153-L156

There is nothing evident here that would affect the age of a character since this would effectively do the same thing for any character connecting to the server, do you have entries under `public.events` in pgSQL?

**Comment by halexys** [comment]
oh, thas is it, i dont have public.events cuz it doesn't appear in the patch-chema or migrations

**Comment by sekaiwish** [comment]
`public.events` was added using the [feature/festa schema](https://github.com/ZeruLight/Erupe/blob/main/patch-schema/festa.sql)
